#version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: built
    volumes:
      - .:/opt/app/api
    environment:
      API_SERVER_ADDR: ":3000"
      DATABASE_URL: "postgres://local-dev@db/api?sslmode=disable"
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: local-dev
      POSTGRES_HOST_AUTH_METHOD: trust
#      POSTGRES_PASSWORD: mypassword
  migrate: &base-migrate
    profiles: [ "tools" ]
    image: migrate/migrate
    entrypoint: "migrate -database postgresql://local-dev@db/api?sslmode=disable -path /tmp/migrations"
    command: up
    links:
      - db
    volumes:
      - ./migrations:/tmp/migrations
  create-migration:
    <<: *base-migrate
    entrypoint: migrate create -dir /tmp/migrations -ext sql
    command: ""
    volumes:
      - ./migrations:/tmp/migrations
    depends_on:
      - db
volumes:
  data:
