services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: built
    volumes:
      - .:/opt/app/api
    environment:
      API_SERVER_ADDR: ":3000"
      DATABASE_URL: postgres://local-dev@db/api?sslmode=disable
    ports:
      - "${API_SERVER_PORT}:${API_SERVER_PORT}"
    env_file:
      - ./.env
    links:
      - db
#    depends_on:
#      - db
  db:
    image: postgres:13-alpine
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_DATABASE_NAME}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_HOST_AUTH_METHOD: ${PG_AUTH_METHOD}
  migrate: &basemigrate
    profiles: [ "tools" ]
    image: migrate/migrate
    entrypoint: "migrate -database postgresql://local-dev@db/api?sslmode=disable -path /tmp/migrations"
    command: up
    links:
      - db
    volumes:
      - ./migrations:/tmp/migrations

  create-migration:
    <<: *basemigrate
    entrypoint: migrate create -dir /tmp/migrations -ext sql
    command: ""
#    volumes:
#      - ./migrations:/tmp/migrations
#    depends_on:
#      - db
volumes:
  data: